# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc2bb5d6c5efaad3b4a08d272403acaa231883ce6f7532739d2bfdeda4ca020dc9ab9ac0bf860e4b0851fd530a15f3fb105655a7443ac631e4f20685a4187b80

test:
  secret_key_base: 77ac53c4deaa4e336ddc094ac6208ccb44739a258163c7e65ca06033a4113069a12e77e01c598e7937a3db36cf8d85e078c1fdf2e6e046b34ce58dc188601e96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
